stages:
  prepare_categories:
    cmd: uv run scripts/prepare_categories.py
    deps:
      - scripts/prepare_categories.py
      - ${prepare_categories.category_tree_path}
    outs:
      - ${prepare_categories.output_dir_path}/categories.parquet
      - ${prepare_categories.output_dir_path}/categories_metadata.json
    params:
      - prepare_categories.category_tree_path
      - prepare_categories.output_dir_path
  prepare_sessions:
    cmd: uv run scripts/prepare_sessions.py
    deps:
      - scripts/prepare_sessions.py
      - ${prepare_sessions.events_path}
    outs:
      - ${prepare_sessions.output_dir_path}/sessions.parquet
      - ${prepare_sessions.output_dir_path}/event_ids.json
    params:
      - prepare_sessions.events_path
      - prepare_sessions.output_dir_path
  prepare_item_properties:
    cmd: uv run scripts/prepare_item_properties.py
    deps:
      - scripts/prepare_item_properties.py
      - ${prepare_item_properties.item_properties_part1_path}
      - ${prepare_item_properties.item_properties_part2_path}
    outs:
      # - ${prepare_item_properties.output_dir_path}/item_properties_values_encoded.parquet
      - ${prepare_item_properties.output_dir_path}/item_properties.parquet
      - ${prepare_item_properties.output_dir_path}/item_properties_metadata.json
    params:
      - prepare_item_properties.item_properties_part1_path
      - prepare_item_properties.item_properties_part2_path
      - prepare_item_properties.output_dir_path
  featurize:
    cmd: uv run scripts/featurize.py
    deps:
      - scripts/featurize.py
      - ${featurize.categories_path}
      - ${featurize.item_properties_path}
      - ${featurize.sessions_path}
    outs:
      - ${featurize.output_dir_path}/enriched_sessions.parquet
      - ${featurize.output_dir_path}/metadata.json
    params:
      - featurize.categories_path
      - featurize.item_properties_path
      - featurize.sessions_path
      - featurize.output_dir_path
      - featurize.categories_metadata_path
      - featurize.item_properties_metadata_path
  train_baseline_model:
    cmd: uv run scripts/train_baseline_model.py
    deps:
      - scripts/train_baseline_model.py
      - ${train_baseline_model.enriched_sessions_path}
      - ${train_baseline_model.metadata_path}
    outs:
      - ${train_baseline_model.output_dir_path}/two_tower_recommender_baseline_model_v${train_baseline_model.model_version}.pkl
    params:
      - train_baseline_model.enriched_sessions_path
      - train_baseline_model.metadata_path
      - train_baseline_model.output_dir_path
      - train_baseline_model.batch_size
      - train_baseline_model.learning_rate
      - train_baseline_model.num_epochs
      - train_baseline_model.output_dim
      - train_baseline_model.model_version
